# Site settings
title: Ticary Solutions
email: contact@ticary.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ticary.com" # the base hostname & protocol for your site
twitter_username: ticary
# github_username:  ticary

# Build settings
markdown: kramdown
include: ['_pages']
include: ['portfolio']
# paginate: 4
# paginate_path: "page:num/"
